/*
*    main.js
*    Mastering Data Visualization with D3.js
*    3.10 - Axes and labels
*/

var margin = { left:100, right:10, top:10, bottom:150 };

var width = 600 - margin.left - margin.right,
    height = 400 - margin.top - margin.bottom;

var g = d3.select("#chart-area")
    .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
    .append("g")
        .attr("transform", "translate(" + margin.left 
            + ", " + margin.top + ")");

// NEW CODE FOR LABELS:
// X Label
g.append("text") // Add some text
    .attr("class", "x axis-label")
    .attr("x", width / 2) // position text halfway through
    .attr("y", height + 140) // push it to the bottom
    .attr("font-size", "20px")
    .attr("text-anchor", "middle") // anchor point in middle to center text
    .text("The word's tallest buildings"); // text to display

// Y Label
g.append("text")
    .attr("class", "y axis-label")
    .attr("x", - (height / 2)) // NB: Because we rotate the same time we
    // set these values, we swap our x and y positions
    .attr("y", -60)
    .attr("font-size", "20px")
    .attr("text-anchor", "middle")
    .attr("transform", "rotate(-90)") // Rotate to make vertical
    .text("Height (m)");

d3.json("data/buildings.json").then(function(data){
    console.log(data);

    data.forEach(function(d){
        d.height = +d.height;
    });

    var x = d3.scaleBand()
        .domain(data.map(function(d){ return d.name; }))
        .range([0, width])
        .paddingInner(0.3)
        .paddingOuter(0.3);

    var y = d3.scaleLinear()
        .domain([0, d3.max(data, function(d){
            return d.height;
        })])
        .range([0, height]);

    // NEW CODE: X AND Y AXIS DEFINED HERE:
    var xAxisCall = d3.axisBottom(x); 
    g.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0, " + height + ")") // Move from top to bottom
        .call(xAxisCall) // invoke our x axis
    .selectAll("text") // grab all text generated by our call on xAxis
        .attr("y", "10")
        .attr("x", "-5")
        .attr("text-anchor", "end")
        .attr("transform", "rotate(-40)"); // add a transform to each text, and 
        // rotate -40 in the clockwise direction (40 degree anticlcokwise)

    var yAxisCall = d3.axisLeft(y)
        .ticks(3)
        .tickFormat(function(d){ // add a m for meter
            return d + "m";
        });
    g.append("g")
        .attr("class", "y-axis")
        .call(yAxisCall);

    var rects = g.selectAll("rect")
        .data(data)
    
    rects.enter()
        .append("rect")
            .attr("y", 0)
            .attr("x", function(d){ return x(d.name); })
            .attr("width", x.bandwidth)
            .attr("height", function(d){ return y(d.height); })
            .attr("fill", "grey");

})